apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cilium
  namespace: argocd
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          argocd.argoproj.io/secret-type: cluster # Target all remote clusters (not the management cluster itself)
  template:
    metadata:
      name: '{{name}}-cilium'
    spec:
      project: addons
      source:
        targetRevision: HEAD
        repoURL: https://github.com/alleaffengaffen/addons.git
        path: cilium
        helm:
          valueFiles:
          - values.yaml
      destination:
        server: '{{server}}'
        namespace: kube-system
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
