external-secrets:
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 1000
    seccompProfile:
      type: RuntimeDefault

  resources:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      cpu: 1
      memory: 500Mi

  priorityClassName: "system-cluster-critical"

  webhook:
    priorityClassName: "system-cluster-critical"

    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 1000
      seccompProfile:
        type: RuntimeDefault

    resources:
      requests:
        cpu: 10m
        memory: 32Mi
      limits:
        cpu: 1
        memory: 500Mi

  certController:
    priorityClassName: "system-cluster-critical"

    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 1000
      seccompProfile:
        type: RuntimeDefault

    resources:
      requests:
        cpu: 10m
        memory: 32Mi
      limits:
        cpu: 1
        memory: 500Mi
