cert-manager:
  global:
    priorityClassName: ""

    # Set the verbosity of cert-manager. Range of 0 - 6 with 6 being the most verbose.
    logLevel: 2

  installCRDs: true
  # When this flag is enabled, secrets will be automatically removed when the certificate resource is deleted
  enableCertificateOwnerRef: true

  resources:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      cpu: 1
      memory: 500Mi

  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault

  containerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    readOnlyRootFilesystem: true
    runAsNonRoot: true

  webhook:
    securityContext:
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault

    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: true
      runAsNonRoot: true

    resources:
      requests:
        cpu: 10m
        memory: 32Mi
      limits:
        cpu: 1
        memory: 500Mi

  cainjector:
    enabled: true
    securityContext:
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault

    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: true
      runAsNonRoot: true

    resources:
      requests:
        cpu: 10m
        memory: 32Mi
      limits:
        cpu: 1
        memory: 500Mi

  startupapicheck:
    enabled: true
    securityContext:
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault

    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: true
      runAsNonRoot: true

    resources:
      requests:
        cpu: 10m
        memory: 32Mi
      limits:
        cpu: 1
        memory: 500Mi
