apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-nginx-funnel
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/funnel: "true"
    tailscale.com/host: "ingress-nginx-l-t"
    tailscale.com/tags: "tag:funnel,tag:k8s"
spec:
  ingressClassName: tailscale
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ingress-nginx-controller
                port:
                  number: 443
  tls:
    - hosts:
        - ingress-nginx-l-t
