external-dns:
  podSecurityContext:
    fsGroup: 65534
    seccompProfile:
      type: RuntimeDefault

  securityContext:
    allowPrivilegeEscalation: false
    runAsNonRoot: true
    runAsUser: 65534
    readOnlyRootFilesystem: true
    capabilities:
      drop: ["ALL"]

  priorityClassName: "infra"

  interval: 1m
  triggerLoopOnEvent: true

  sources:
    - service
    - ingress

  policy: sync
  registry: txt
  # When using a registry other than "noop", specifies a name that
  # uniquely identifies this instance of external-dns.
  txtOwnerId: "external-dns-l-t"

  domainFilters: []

  provider: designate

  env:
    - name: OS_AUTH_URL
      value: https://api.pub0.infomaniak.cloud/identity
    - name: OS_REGION_NAME
      value: dc3-a
    - name: OS_USERNAME
      valueFrom:
        secretKeyRef:
          name: openstack-creds
          key: openstack_user
    - name: OS_PASSWORD
      valueFrom:
        secretKeyRef:
          name: openstack-creds
          key: openstack_password
    - name: OS_PROJECT_NAME
      valueFrom:
        secretKeyRef:
          name: openstack-creds
          key: openstack_project
