---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: clusters
  namespace: argocd
spec:
  description: Project contains the cluster of clusters and all clusters
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: 'https://kubernetes.default.svc'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clusters
spec:
  destination:
    name: ''
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  source:
    path: apps
    repoURL: 'https://github.com/alleaffengaffen/clusters.git'
    targetRevision: HEAD
  project: clusters
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
