apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: traefik-funnel
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/funnel: "true"
    tailscale.com/host: "traefik-l-t"
    tailscale.com/tags: "tag:funnel,tag:k8s"
spec:
  ingressClassName: tailscale
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: traefik
                port:
                  number: 443
  tls:
    - hosts:
        - traefik-l-t
