apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: traefik-kube-system
    app.kubernetes.io/name: traefik
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/funnel: "true"
  name: traefik-funnel
  namespace: kube-system
spec:
  loadBalancerClass: tailscale
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ports:
    - name: web
      port: 80
      protocol: TCP
      targetPort: web
    - name: websecure
      port: 443
      protocol: TCP
      targetPort: websecure
  selector:
    app.kubernetes.io/instance: traefik-kube-system
    app.kubernetes.io/name: traefik
  sessionAffinity: None
  type: LoadBalancer
