apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tailscale-operator
  namespace: argocd
spec:
  destination:
    namespace: tailscale
    server: https://kubernetes.default.svc
  project: default
  source:
    path: tailscale
    repoURL: https://github.com/alleaffengaffen/l-t
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true 
      selfHeal: true 
      allowEmpty: false 
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
