name: Create hetzner-k3s cluster

on:
  workflow_dispatch:
    inputs:
      name:
        type: string
        default: ""
        description: Name of the cluster
      master_count:
        type: choice
        default: "1"
        options:
        - "1"
        - "3"
        description: Number of control-plane instances to deploy
      worker_count:
        type: string
        default: "1"
        description: Number of worker nodes to deploy
      worker_type:
        type: choice
        default: cax11
        options:
          - cx11
          - cpx11
          - cx21
          - cpx21
          - cx31
          - cpx31
          - cax11
          - cax21
          - cax31
        description: Size of the worker instances to create (cax=arm64)
      location:
        type: choice
        default: hel1
        options:
          - hel1
          - fsn1
          - nbg1
          - ash
          - hil
        description: Location to deploy the cluster
      k3s_version:
        type: choice
        default: "1.28"
        options:
        - "1.24"
        - "1.25"
        - "1.25"
        - "1.26"
        - "1.27"
        - "1.28"
        description: Version of k3s to deploy
      
env:
  STATE_BUCKET: "grapesstate"
  STATE_BUCKET_REGION: "eu-west-1" 

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write
      contents: read
    steps:
    - uses: actions/checkout@v4
    - name: Fetch secrets from AKeyless
      id: fetch-secrets
      uses: LanceMcCarthy/akeyless-action@v3
      with:
        access-id: ${{ secrets.AKEYLESS_ACCESS_ID}}
        static-secrets: '{"/actions/grapes/hcloud_token":"HCLOUD_TOKEN"}'
    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::351425708426:role/grapes
        role-session-name: grapes
        aws-region: ${{ env.STATE_BUCKET_REGION }}
    - name: Create output directory
      run: mkdir output
    - name: Setup hetzner-k3s cli
      run: |
        curl -fsSL -o /tmp/hetzner-k3s-linux-amd64 https://github.com/vitobotta/hetzner-k3s/releases/latest/download/hetzner-k3s-linux-amd64
        sudo install -m 555 /tmp/hetzner-k3s-linux-amd64 /usr/local/bin/hetzner-k3s
        hetzner-k3s --version
    - name: Setup go-template-cli
      run: |
        curl -fsSL -o /tmp/tpl https://github.com/bluebrown/go-template-cli/releases/latest/download/tpl-linux-amd64
        sudo install -m 555 /tmp/tpl /usr/local/bin/tpl
        tpl --version
    - name: Setup helm
      run: |
        curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
        chmod 700 get_helm.sh
        ./get_helm.sh
        rm get_helm.sh
        helm version
        helm repo add cilium https://helm.cilium.io
    - name: Generate SSH key
      run: |
        ssh-keygen -q -t ed25519 -C "${{ github.event.inputs.name }} hetzner-k3s" -f "output/id_ed25519" -N ""
        curl -fsSL https://github.com/$GITHUB_ACTOR.keys | tee -a "output/id_ed25519.pub"
    - name: Calculate k3s Version
      run:  echo "K3S_RELEASE=$(hetzner-k3s releases | grep -v "rc" | grep ${{ github.event.inputs.k3s_version }} | tail -n 1)" >> $GITHUB_ENV
    - name: Template configs
      run: |
        cat <<EOF | tpl -f hetzner-k3s/hetzner-k3s.yaml > output/cluster-config.yaml
        {
          "name": "${{ github.event.inputs.name }}",
          "k3s_version": "${{ env.K3S_RELEASE }}",
          "location": "${{ github.event.inputs.location }}",
          "worker_type": "${{ github.event.inputs.worker_type }}",
          "worker_count": "${{ github.event.inputs.worker_count }}",
          "master_count": "${{ github.event.inputs.master_count }}"
        }
        EOF
        cat <<EOF | tpl -f hetzner-k3s/cilium-values.yaml > output/cilium-values.yaml
        {
          "master_count": "${{ github.event.inputs.master_count }}"
        }
        EOF
    - name: Create cluster
      run: hetzner-k3s create --config output/cluster-config.yaml
    - name: Install cilium
      env:
        KUBECONFIG: output/kubeconfig
      run: helm upgrade -i cilium -n kube-system cilium/cilium -f output/cilium-values.yaml
    - name: Upload outputs to s3
      run: aws s3 cp output s3://${{ env.STATE_BUCKET }}/${{ github.event.inputs.name }}-outputs --recursive