name: Delete eks-terraform cluster

on:
  workflow_dispatch:
    inputs:
      name:
        type: string
        default: ""
        description: Name of the cluster

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write
      contents: read
    env:
      STATE_BUCKET: "grapes-state"
      STATE_BUCKET_REGION: "eu-west-1"
    steps:
    - uses: unfor19/install-aws-cli-action@v1
    - uses: actions/checkout@v4
    - name: Fetch secrets from AKeyless
      id: fetch-secrets
      uses: LanceMcCarthy/akeyless-action@v3
      with:
        access-id: ${{ secrets.AKEYLESS_ACCESS_ID }}
        static-secrets: '{"/actions/grapes/aws_access_key":"AWS_ACCESS_KEY_ID", "/actions/grapes/aws_secret_access_key": "AWS_SECRET_ACCESS_KEY"}'
    - name: Create Terraform backend configuration
      run: |
        tee eks-terraform/s3.tfbackend << END
          bucket = "${{ env.STATE_BUCKET }}"
          key    = "${{ github.event.inputs.name }}"
          region = "${{ env.STATE_BUCKET_REGION }}"
        END
    - name: Grab variables file from s3
      uses: keithweaver/aws-s3-github-action@v1.0.0
      with:
        command: mv
        source: s3://${{ env.STATE_BUCKET }}/${{ github.event.inputs.name }}.tfvars
        destination: eks-terraform/${{ github.event.inputs.name }}.tfvars
        aws_access_key_id: ${{ env.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ env.AWS_SECRET_ACCESS_KEY }}
        aws_region: ${{ env.STATE_BUCKET_REGION }}
    - name: Setup terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.6.3
        terraform_wrapper: false
    - name: Terraform Init
      id: init
      run: terraform -chdir=eks-terraform init -backend-config=s3.tfbackend
    - name: Terraform Destroy
      run: terraform -chdir=eks-terraform destroy -auto-approve -input=false -var-file ${{ github.event.inputs.name }}.tfvars
    - name: Delete state
      uses: keithweaver/aws-s3-github-action@v1.0.0
      with:
        command: rm
        source: s3://${{ env.STATE_BUCKET }}/${{ github.event.inputs.name }}
        aws_access_key_id: ${{ env.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ env.AWS_SECRET_ACCESS_KEY }}
        aws_region: ${{ env.STATE_BUCKET_REGION }}