name: Delete hetzner-k3s cluster

on:
  workflow_dispatch:
    inputs:
      name:
        type: string
        default: ""
        description: Name of the cluster

jobs:
  destroy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write
      contents: read
    steps:
    - uses: actions/checkout@v3
    - name: Fetch secrets from AKeyless
      id: fetch-secrets
      uses: LanceMcCarthy/akeyless-action@v3
      with:
        access-id: ${{ secrets.AKEYLESS_ACCESS_ID}}
        static-secrets: '{"/alleaffengaffen/actions/grapes/hcloud_token":"HCLOUD_TOKEN"}'
    - name: Setup hetzner-k3s cli
      run: |
        curl -fsSL -o /tmp/hetzner-k3s-linux-amd64 https://github.com/vitobotta/hetzner-k3s/releases/latest/download/hetzner-k3s-linux-amd64
        sudo install -m 555 /tmp/hetzner-k3s-linux-amd64 /usr/local/bin/hetzner-k3s
        hetzner-k3s --version
    - name: Download outputs
      id: download-artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        workflow: create-hetzner-k3s.yml
        # Optional, the status or conclusion of a completed workflow to search for
        # Can be one of a workflow conclusion:
        #   "failure", "success", "neutral", "cancelled", "skipped", "timed_out", "action_required"
        # Or a workflow status:
        #   "completed", "in_progress", "queued"
        # Use the empty string ("") to ignore status or conclusion in the search
        workflow_conclusion: success
        # Optional, will get head commit SHA
        pr: ${{github.event.pull_request.number}}
        # Optional, no need to specify if PR is
        commit: ${{github.event.pull_request.head.sha}}
        # Optional, will use the specified branch. Defaults to all branches
        branch: master
        # Optional, defaults to all types
        event: push
        # Optional, will use specified workflow run
        # use ${{ github.event.workflow_run.id }} when your action runs in a workflow_run event
        # and wants to download from the triggering workflow run
        run_id: 1122334455
        # Optional, run number from the workflow
        run_number: 34
        # Optional, uploaded artifact name,
        # will download all artifacts if not specified
        # and extract them into respective subdirectories
        # https://github.com/actions/download-artifact#download-all-artifacts
        # is treated as a regular expression if input name_is_regexp is true
        # will download only those artifacts with a name that matches this regular expression
        # https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_expressions
        name: artifact_name
        # Optional, name is treated as a regular expression if set true
        name_is_regexp: true
        # Optional, a directory where to extract artifact(s), defaults to the current directory
        path: extract_here
        # Optional, defaults to current repo
        repo: ${{ github.repository }}
        # Optional, check the workflow run to whether it has an artifact
        # then will get the last available artifact from the previous workflow
        # default false, just try to download from the last one
        check_artifacts: false
        # Optional, search for the last workflow run whose stored an artifact named as in `name` input
        # default false
        search_artifacts: false
        # Optional, choose to skip unpacking the downloaded artifact(s)
        # default false
        skip_unpack: false
        # Optional, choose how to exit the action if no artifact is found
        # can be one of:
        #  "fail", "warn", "ignore"
        # default fail
        if_no_artifact_found: fail
        # Optional, ignore forks when searching for artifacts
        # default true
        allow_forks: false
    - name: Delete cluster
      run: hetzner-k3s delete --config output/cluster-config.yaml