name: Delete hetzner-k3s cluster

on:
  workflow_dispatch:
    inputs:
      name:
        type: string
        default: ""
        description: Name of the cluster
    
env:
  STATE_BUCKET: "grapesstate"
  STATE_BUCKET_REGION: "eu-west-1" 

jobs:
  destroy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write
      contents: read
    steps:
    - uses: actions/checkout@v4
    - uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::351425708426:role/gh-grapes
        role-session-name: grapes
        aws-region: ${{ env.STATE_BUCKET_REGION }}
    - name: Fetch secrets from AKeyless
      id: fetch-secrets
      uses: LanceMcCarthy/akeyless-action@v3
      with:
        access-id: ${{ secrets.AKEYLESS_ACCESS_ID}}
        static-secrets: '{"/actions/grapes/hcloud_token":"HCLOUD_TOKEN"}'
    - name: Setup hetzner-k3s cli
      run: |
        curl -fsSL -o /tmp/hetzner-k3s-linux-amd64 https://github.com/vitobotta/hetzner-k3s/releases/latest/download/hetzner-k3s-linux-amd64
        sudo install -m 555 /tmp/hetzner-k3s-linux-amd64 /usr/local/bin/hetzner-k3s
        hetzner-k3s --version
    - name: Download outputs
      run: |
        aws s3 mv s3://${{ env.STATE_BUCKET }}/${{ github.event.inputs.name }}-outputs output --recursive
    - name: Delete cluster
      run: hetzner-k3s delete --config output/cluster-config.yaml
