argo-cd:
  global:
    networkPolicy:
      create: true

  configs:
    params:
      server.insecure: true
      timeout.reconciliation: 20
    cm:
      url: "https://cd.technat.dev"
      server.rbac.log.enforce.enable: "true"
      exec.enabled: "true"
      admin.enabled: "true"
      dex.config: |
        connectors:
          - type: github
            id: github
            name: GitHub
            config:
              clientID: $github-oidc:client_id
              clientSecret: $github-oidc:client_secret 
              orgs:
              - name: alleaffengaffen
    rbac:
      policy.csv: |
        # Grant all members of 'alleaffengaffen:orangutans' admins
        g, alleaffengaffen:orangutans, role:admin
      policy.default: role:readonly

  server:
    ingress:
      enabled: true
      annotations:
        ingress.kubernetes.io/force-ssl-redirect: "true"
        cert-manager.io/cluster-issuer: letsencrypt-production
      ingressClassName: "traefik"
      hosts:
        - cd.technat.dev
      tls:
        - secretName: argocd-secret
          hosts:
            - cd.technat.dev
    priorityClassName: "system-cluster-critical"
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop: ["ALL"]
      readOnlyRootFilesystem: true
      runAsNonRoot: true
    metrics:
      enabled: true
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 50m
        memory: 64Mi

  controller:
    enableStatefulSet: true
    priorityClassName: "system-cluster-critical"
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop: ["ALL"]
      readOnlyRootFilesystem: true
      runAsNonRoot: true
    metrics:
      enabled: true
    resources:
      limits:
        cpu: 1
        memory: 1Gi
      requests:
        cpu: 50m
        memory: 128Mi

  notifications:
    priorityClassName: "system-cluster-critical"
    containerSecurityContext:
      runAsNonRoot: true
      readOnlyRootFilesystem: true
      allowPrivilegeEscalation: false
      seccompProfile:
        type: RuntimeDefault
      capabilities:
        drop:
          - ALL
    metrics:
      enabled: true
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 50m
        memory: 64Mi

  redis:
    priorityClassName: "system-cluster-critical"
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop: ["ALL"]
      readOnlyRootFilesystem: true
      runAsNonRoot: true
    metrics:
      enabled: true
      resources:
        limits:
          cpu: 100m
          memory: 128Mi
        requests:
          cpu: 5m
          memory: 16Mi
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 50m
        memory: 64Mi

  repoServer:
    priorityClassName: "system-cluster-critical"
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop: ["ALL"]
      readOnlyRootFilesystem: true
      runAsNonRoot: true
    metrics:
      enabled: true
    resources:
      limits:
        cpu: 1
        memory: 1Gi
      requests:
        cpu: 50m
        memory: 64Mi

  applicationSet:
    priorityClassName: "system-cluster-critical"
    containerSecurityContext:
      runAsNonRoot: true
      readOnlyRootFilesystem: true
      allowPrivilegeEscalation: false
      seccompProfile:
        type: RuntimeDefault
      capabilities:
        drop:
          - ALL
    metrics:
      enabled: true
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 50m
        memory: 64Mi
